FROM registry.fedoraproject.org/fedora-minimal:39

LABEL maintainer="sbanwart@acm.org"
LABEL version="4.1"
LABEL description="A container for running the jrnl tool. https://jrnl.sh/"

RUN microdnf update -y && \
    microdnf install -y python3-pip shadow-utils && \
    pip3 install --no-cache-dir jrnl==4.1 && \
    microdnf clean all && \
    rm -rf /var/cache/yum

RUN useradd jrnl

USER jrnl

ENTRYPOINT [ "jrnl" ]
