FROM registry.fedoraproject.org/fedora-minimal:39

LABEL maintainer="sbanwart@acm.org"
LABEL version="0.23.4"
LABEL description="A container for running the Diagrams drawing tool. https://diagrams.mingrammer.com/"

RUN microdnf update -y && \
    microdnf install -y graphviz python3-pip python3-devel shadow-utils gcc && \
    pip install --no-cache-dir diagrams==0.23.4 && \
    microdnf clean all && \
    rm -rf /var/cache/yum && \
    mkdir -p /data

RUN useradd diagrams

WORKDIR /data

USER diagrams

ENTRYPOINT [ "python3" ]
